D-Order/2025-d-order-fe-admin-v2

- src/pages/liveOrder/LiveOrderPage.tsx
- src/pages/liveOrder/_components/OrderStateBtn.tsx
- src/pages/liveOrder/_components/menuList/LiveOrderMenuList.tsx
- src/pages/liveOrder/_components/tableList/LiveOrderTableList.tsx
- src/pages/liveOrder/_components/tableList/TableBill.tsx
- src/pages/liveOrder/_components/tableList/TableBillItem.tsx
- src/pages/liveOrder/dummy/DummyLiveOrderService.ts
- src/pages/liveOrder/hooks/useLiveOrdersData.ts
liveOrder페이지 api연결부분 더미함수연결, 코드구조 리팩토링
기존애니메이션 작동안되는부분 수정하고 UI페이지에서 여러 책임이 들어있던것을 훅으로 일단 옮겨놨습니다. 아직 bills에서 주문이 전부 사라질때 오류가 좀 있어 리팩토링 완료하고 디자인 수정된대로 주방과 서버 분리하겠습니다. 
- #8
> ♻️ [Refactor] #8 - liveOrder 더미함수연결, 코드구조 리팩토링

- src/pages/liveOrder/LiveOrderPage.tsx
- src/pages/liveOrder/_components/tableList/LiveOrderTableList.tsx
- src/pages/liveOrder/_components/tableList/TableBill.tsx
- src/pages/liveOrder/_components/tableList/TableBillItem.tsx
- src/pages/liveOrder/dummy/DummyLiveOrderService.ts
- src/pages/liveOrder/hooks/useLiveOrdersData.ts
https://github.com/user-attachments/assets/117ee1ab-58b0-4861-b75c-699b26dd4126
#11
> [Refactor] #11 - 메인 페이지 애니메이션 적용

- src/pages/tableView/TableViewPage.tsx
- src/pages/tableView/_apis/getTableList.ts
- src/pages/tableView/_components/tableCard.tsx
- src/pages/tableView/_components/tableComponents.styled.ts
- src/pages/tableView/_components/tableGrid.tsx
- src/pages/tableView/_mocks/dummyTableDetail.ts
- src/pages/tableView/_mocks/dummyTableList.ts
refactor : 테이블 뷰 페이지 반응형 리펙토링 & 입장 시간 반영 색 처리"
> Refactor/#9 refactor : 테이블 뷰 페이지 반응형 리펙토링 & 입장 시간 반영 색 처리"

- src/constants/imageConstants.ts
- src/pages/coupon/CouponPage.styled.ts
- src/pages/coupon/CouponPage.tsx
- src/pages/coupon/_components/Coupon.styled.ts
- src/pages/coupon/_components/CouponCreateCard.tsx
- src/pages/coupon/_components/CouponRegisterModa.tsx
- src/pages/coupon/api/LoadingSpinner.tsx
- src/pages/modal_test_view/_components/MenuModal.tsx
쿠폰 등록 화면 초기 페이지 디자인 완성하였습니다.
닫기 버튼 위치 이상해서 수정해야합니다..
#17
> [Design] : 쿠폰 등록하기 페이지 UI 생성 / 쿠폰 등록 모달창 UI 완성

- src/components/header/Header.tsx
- src/components/header/_components/BellModal.tsx
헤더 직원호출 알림소리 로직 클릭이벤트 로직없어도 가능해서 로직 수정 벨 모달 ui변경 
- #28
> 🔧  [Fix] #28 - 헤더 벨소리 로직수정 벨 ui수정

- src/pages/menu/_components/MenuCreateCard.tsx
- vite.config.js
빌드오류 수정 - 쓰지않고 임포트해둔 타입 지웠습니다. 
- #52
> 🐛  [Fix] #52 - 빌드오류 수정

- src/pages/mypage/MyPage.tsx
- src/pages/mypage/apis/getManagerPatch.ts
- src/pages/mypage/apis/getQRDownload.ts
- src/pages/mypage/components/SeatFeeField.tsx
- QR 생성 api 수정
- 마이페이지 테이블 이용료 api 수정
- #63
> [Fix] 1차 QR

- src/pages/modal_test_view/_components/EditMenuModal.tsx
- src/pages/modal_test_view/_components/EditSetMenuModal.tsx
- src/pages/modal_test_view/_components/MenuModal.tsx
- src/pages/modal_test_view/_components/styled.ts
|                 이미지1                 |                 이미지2                 |
| :-------------------------------------: | :-------------------------------------: |
| <img src="[이미지경로1]" width="300" /> | <img src="[이미지경로2]" width="300" /> |
- ex) #60
> 🔧 [Refactor]/60

- src/components/header/Header.tsx
- src/components/header/hooks/useBoothRevenue.ts
헤더 api오류 수정합니다.  기존에 있던 에러때문에 나중에 연결성공해도 값이 표시가 안되는 문제 수정 
- #72
> 🐛 [Fix] #72 - api연결 오류 수정

- src/pages/tableView/_modal/ResetModal.tsx
fix : QA 테이블 맞춤법 수정 / WS check
- #63
> fix : QA 테이블 맞춤법 수정 / WS check

- src/pages/liveorder_v2/LiveOrderStore.ts
> 🐛 [Fix] #72 - 태블릿터치오류수정

- src/pages/liveorder_v2/LiveOrderStore.ts
- src/pages/tableView/_apis/getTableDetail.ts
- src/pages/tableView/_apis/updateOrderQuantity.ts
- src/pages/tableView/_components/detailPage/tableDetail.tsx
- src/pages/tableView/_hooks/useTableDetail.ts
- src/pages/tableView/_modal/CancelConfirmModal.tsx
> 🚀 [Deploy]

- src/pages/liveorder_v2/LiveOrderStore.ts
- src/pages/modal_test_view/_components/MenuModal.tsx
> 🚒 [HotFix] #72 - 음료막기

- src/constants/timeConstant.ts
> ♻️ [Refactor] #72 사라지는시간3분으로 조정

- src/pages/liveorder_v2/LiveOrderStore.ts
- src/pages/liveorder_v2/_components/tablelist/TableBill.tsx
- src/pages/liveorder_v2/_components/tablelist/TableList.tsx
- src/pages/liveorder_v2/hooks/useGroupedAndSortedOrders.ts
빌지 사라질때 페이드아웃 추가했습니다! 
- ex) #72
> ♻️ [:태블릿 애니메이션 수정

- src/pages/liveorder_v2/LiveOrderStore.ts
- src/pages/liveorder_v2/_components/OrderStateBtn.tsx
모바일 터치이벤트 오류 onTouchStart 핸들러를 추가하고,
버튼 스타일에 touch-action, z-index를 명확히 지정해 봤습니다.. 
- #72
> 🐛 [Fix] #72 - 태블릿 버튼 클릭오류 2차수정

- src/pages/liveorder_v2/_components/OrderStateBtn.tsx
실시간주문 상태버튼클릭오류 수정했습니다. 
event.preventDefault()를 호출하여, 이후에 발생하는 onClick 이벤트를 막는방법을 적용해봤습니다.. 
- #72
> 🐛 [Fix] #72 - 실시간주문 상태버튼클릭오류 수정

- src/pages/liveorder_v2/_components/OrderStateBtn.tsx
> 🐛 [Fix] #72 태블릿 버튼터치오류

- src/pages/liveorder_v2/_components/OrderStateBtn.tsx
> 🐛 [Fix] #72-  버튼수정..

- src/pages/tableView/_components/detailPage/tableDetail.tsx
QA 주문취소 : 세트메뉴 취소 - type 처리
- #63
> QA 주문취소 : 세트메뉴 취소 - type 처리

- src/pages/liveorder_v2/LiveOrderStore.ts
- src/pages/liveorder_v2/_components/OrderStateBtn.tsx
클릭중복 방지용으로 잠금걸어놨던 로직을 서빙완료에서만 풀었습니다.. 
- #72
> 🐛 [Fix] #72 - 버튼 마지막수정

- src/pages/login/_components/inputs/CommonInput.styled.ts
- src/pages/signup/_components/inputs/CommonInput.styled.ts
> [Fix] #138 - 비밀번호 입력 창 오류 수정

- src/pages/liveorder_v2/LiveOrderStore.ts
> 🐛 [Fix] #72배포오류수정

- src/pages/liveorder_v2/LiveOrderStore.ts
중복클릭 방지 로직이 크롬에서는 잘못동작하고 있는것 같아 제외하는 로직을 추가하였습니다. 
- #72
> 🐛 [Fix] #72 - 크롬환경 터치오류 수정

- src/pages/liveorder_v2/LiveOrderStore.ts
- src/pages/liveorder_v2/services/LiveOrderWebSocketService.ts
크롬 제외코드가 웹소켓 핸들러에서는 빠져있어서 추가했습니다. 
- #72
> 🐛 [Fix] #72 - 웹소켓 핸들러수정

- src/pages/liveorder_v2/LiveOrderStore.ts
수정중 페이드아웃이 안되는 문제가 있어 크롬에서 잠금해제 푼거는 취소했습니다.
- #72
> 🐛 [Fix] #72 - 실시간주문 버튼터치 수정

- src/pages/liveorder_v2/LiveOrderStore.ts
- src/pages/liveorder_v2/_components/OrderStateBtn.tsx
> 🐛 [Fix] #72 - 태블릿 버튼 터치오류

- src/pages/liveorder_v2/_components/OrderStateBtn.tsx
> 👍 [Fix] #72 - 버튼 클릭 디버깅 추가 

- src/pages/liveorder_v2/LiveOrderStore.ts
- src/pages/liveorder_v2/_components/OrderStateBtn.tsx
> 🐛 [Fix] #72 -버튼 디버깅텍스트변경

- src/pages/liveorder_v2/_components/OrderStateBtn.tsx
> 🐛 [Fix] #72-  터치인식 수정

- src/pages/liveorder_v2/LiveOrderStore.ts
- src/pages/liveorder_v2/_components/OrderStateBtn.tsx
> 👎 [Fix] #72 - 디버깅메세지 추가

- src/pages/liveorder_v2/services/LiveOrderServiceV2.ts
설마 경로에//두개 겹치는거 크롬만 처리안해줘서그런건 지 확인해봅니다 
- #72
> 🐛 [Fix] #72 api 경로수정

- src/pages/liveorder_v2/LiveOrderStore.ts
웹소켓과 일반 api사이에 타이밍오류가 있는거같아 지연시간을 늘렸습니다. 
- #72
> ✌️ [Fix] #72 지연시간 증가

- src/pages/liveorder_v2/LiveOrderStore.ts
- src/pages/liveorder_v2/_components/OrderStateBtn.tsx
> 💯 [Fix] #72 - 되돌리기 로직변경

- src/pages/liveorder_v2/LiveOrderStore.ts
> 🐛 [Fix] #72 - id사용하도록 수정

- src/pages/liveorder_v2/LiveOrderStore.ts
> 🐛 F[ix] #72 속도지연 반영안됨

- src/pages/tableView/_components/detailPage/tableDetail.tsx
- src/pages/tableView/_modal/CancelMenuModal.tsx
QA: 주문 취소 로직 0에서 시작하도록
- #63 3
> QA: 주문 취소 로직 0에서 시작하도록

- src/pages/liveorder_v2/LiveOrderStore.ts
- src/pages/liveorder_v2/_components/menulist/MenuList.tsx
- src/pages/liveorder_v2/_components/tablelist/TableBill.tsx
- src/pages/liveorder_v2/_components/tablelist/TableList.tsx
- src/pages/liveorder_v2/hooks/useGroupedAndSortedOrders.ts
- src/pages/liveorder_v2/types.ts
> 🐛 [Fix] #72 - 다고침

- src/components/header/BellPlayer.ts
- src/components/header/hooks/useStaffCall.ts
- src/pages/liveorder_v2/LiveOrderPage.tsx
- src/pages/liveorder_v2/LiveOrderStore.ts
- src/pages/liveorder_v2/_components/tablelist/TableBill.tsx
- src/pages/liveorder_v2/types.ts
> 🐛 [Fix] #72 -  벨소리 수정 실시간주문 타이머 수정

- src/pages/tableView/_components/detailPage/tableDetail.tsx
- src/pages/tableView/_modal/CancelErrorModal.tsx
> QA : 에러 메세지 모달

- src/components/header/Header.tsx
- src/components/header/hooks/useBoothRevenue.ts
> 🐛 [Fix] #72 - 헤더 연결끊김문제 수정
